-- Cria a base de dados:
create database STREAMING;

-- Utiliza a base de dados:
use STREAMING;

create table CONTAS(
   ID INT IDENTITY(1,1) NOT NULL,
   NOME_TITULAR VARCHAR (100) NOT NULL,
   EMAIL VARCHAR(100) NOT NULL,
   SENHA VARCHAR(100) NOT NULL,
   DATA_CRIACAO DATE NOT NULL,
   ID_PAGAMENTO INT NOT NULL,
   CONSTRAINT PK_CONTAS PRIMARY KEY(ID)
);
GO

create table TELEFONES(
   ID INT IDENTITY(1,1) NOT NULL,
   DDI INT NOT NULL,
   DDD INT NOT NULL,
   NUMERO INT NOT NULL,
   TIPO CHAR(1) NOT NULL,
   ID_CONTA INT NOT NULL,
   CONSTRAINT PK_TELEFONES PRIMARY KEY(ID)
);
GO

create table PRODUTOS(
   ID INT IDENTITY(1,1) NOT NULL,
   TITULO VARCHAR(100) NOT NULL,
   LANCAMENTO DATE NOT NULL,
   DURACAO TIME NOT NULL,
   SINOPSE VARCHAR(250) NOT NULL,
   CLASSIFICACAO INT NOT NULL,
   DIRETOR VARCHAR(100) NOT NULL,
   GENERO VARCHAR(100) NOT NULL,
   CONSTRAINT PK_PRODUTOS PRIMARY KEY(ID)
);
GO

create table FILMES(
   ID INT IDENTITY(1,1) NOT NULL,
   ID_PRODUTO INT NOT NULL,
   CONSTRAINT PK_FILMES PRIMARY KEY(ID)
);
GO

create table SERIES(
   ID INT IDENTITY NOT NULL,
   ID_PRODUTO INT NOT NULL,
   TEMPORADAS INT NOT NULL,
   SINOPSE VARCHAR(250) NOT NULL,
   CONSTRAINT PK_SERIES PRIMARY KEY(ID)
);
GO

create table EPISODIOS(
   ID INT IDENTITY NOT NULL,
   ID_SERIE INT NOT NULL,
   TITULO VARCHAR(100) NOT NULL,
   DURACAO TIME NOT NULL,
   SINOPSE VARCHAR(250) NOT NULL,
   CONSTRAINT PK_EPISODIOS PRIMARY KEY(ID)
);
GO

create table PAGAMENTOS(
   ID INT IDENTITY NOT NULL,
   TIPO CHAR(1) NOT NULL,
   DESCRICAO VARCHAR(100) NOT NULL,
   DATA_PAGAMENTO DATE NOT NULL,
   CONSTRAINT PK_PAGAMENTOS PRIMARY KEY(ID)
);
GO

create table PERFIS(
   ID INT IDENTITY NOT NULL,
   NOME VARCHAR(100) NOT NULL,
   AVATAR VARCHAR(250) NOT NULL,
   SENHA VARCHAR(100) NOT NULL,
   CONSTRAINT PK_PERFIS PRIMARY KEY(ID)
);
GO

create table ASSISTIR(
   ID INT IDENTITY NOT NULL,
   ID_PERFIL INT NOT NULL,
   ID_PRODUTO INT NOT NULL,
   CONSTRAINT PK_ASSISTIR PRIMARY KEY(ID)
);
GO

create table MINHA_LISTA(
   ID INT IDENTITY NOT NULL,
   ID_PERFIL INT NOT NULL,
   ID_PRODUTO INT NOT NULL,
   CONSTRAINT PK_MINHA_LISTA PRIMARY KEY(ID)
);
GO

create table FAVORITOS(
   ID INT IDENTITY NOT NULL,
   ID_ASSISTIR INT NOT NULL,
   ID_PERFIL INT NOT NULL,
   ID_PRODUTO INT NOT NULL,
   CONSTRAINT PK_FAVORITOS PRIMARY KEY(ID)
);
GO

create table RESTRICOES(
   ID INT IDENTITY NOT NULL,
   ID_PERFIL INT NOT NULL,
   TIPO VARCHAR(100) NOT NULL,
   CONSTRAINT PK_RESTRICOES PRIMARY KEY(ID)
);
GO

create table DOWNLOADS(
   ID INT IDENTITY NOT NULL,
   ID_ASSISTIR INT NOT NULL,
   ID_PERFIL INT NOT NULL,
   ID_PRODUTO INT NOT NULL,
   ARMAZENAMENTO INT NOT NULL,
   CONSTRAINT PK_DOWNLOADS PRIMARY KEY(ID)
);
GO